language: node_js
node_js:
- 8.9.4
script:
- npm install
- npm run bootstrap
- npm run lint
- npm run test
notifications:
  slack:
    secure: tKx7optw2zySASRhtPKi7vgkeaA/ui+K8Gjumhk/bTyULJxwSAaWTpJHkNRqts1KvKGDULMY1gg7sn1BtHSyOp6cnq7SrK+ZZFUIlx2fDrSRyb/uYhBOo/Mca8elJZ+Is9BKz5j14f/dQnEnQpEpH6YqFlTlAdMnYr3PvjAxEQl7rC4P6NbsJLksIjueV4ccdUCUkoseHADvz69sw5mwgGVg/nNOU0uGK3VFBDmPi20KIz7Sxeq+WGwcPRBZgtNqMbRwFsrJKwgRq5YDcMpTHWqMkc8xVPVcfhq38MJwQfdMBngJSnBhduHeCezvs+KQKBxuxKfBxbghbeV/310o4++frKHKc3vixChdjK0OnZiDE61Hqo++Mo11lB1lJAqQoyud3fORfNqMV69V7F+ckY7Ox2l2aqElAZKaDAZqkw+sr6VO0m4iFLr5yYt+L9C3DQ+9DzwHcfITx4n7xBMzpHPbSStUmvvkmUBzuqJc257kYcl2DxFQPUzGhn+VkW+BOj5DB2RrXSKxOUUsKhfTBiAEgrar2Umcpp96h2Aok9P/R9micOTkrdJQH0Kjq2LcgYJ+HZDmKfovt+O2nCMQYGg19iFwd2j2PRDeUP2iRoffQKiuVLP1bNHVPuzbegS5fkpYe0jYM8FVpUmTKlx1iQfTpBy5xOxlnGnqVZG2eQs=
